## Numpy

In [16]:
import numpy as np

arr = np.array([[1,2,3],[4,5,3]])
print(np)


<module 'numpy' from 'C:\\Python311\\Lib\\site-packages\\numpy\\__init__.py'>


In [5]:
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(arr.data)

2
(2, 3)
6
int32
4


In [9]:
arr = np.array([[1,2,3],[4,5,3]], dtype=np.int16)  # set the data types
print(arr)
print(arr.dtype)

[[1 2 3]
 [4 5 3]]
int16


In [14]:
row = np.array([1,2,3])
explicit_row = np.array([[1,2,3]])
explicit_col = np.array([[4],[5],[6]])
print(explicit_row)
print(explicit_col)


[[1 2 3]]
[[4]
 [5]
 [6]]


In [17]:
np.ones((2,2))
np.zeros((2,2))
np.full((3,2), 55)

array([[55, 55],
       [55, 55],
       [55, 55]])

In [18]:
np.linspace(0,99, num=10)

array([ 0., 11., 22., 33., 44., 55., 66., 77., 88., 99.])

In [20]:
np.arange(0, 99, 5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [ ]:
np.add
np.subtract
np.mutiply
np.divide

In [22]:

arr = np.array([[1,2,3],[4,5,6]])
print(np.mean(arr))
print(np.std(arr))
print(np.min(arr))
print(np.max(arr))

3.5
1.707825127659933
1
6


In [23]:
arr.T.shape # transpose the array

(3, 2)

In [25]:
np.reshape(arr,(1,6))

array([[1, 2, 3, 4, 5, 6]])

In [26]:
# np.save np.load

## pandas

In [3]:
import pandas as pd
pd.Series(['a','b','c','c'])

0    a
1    b
2    c
3    c
dtype: object

In [7]:
s = pd.Series(['a','b','c','c'],
         index=['r1','r2','r3','r4']
         )

In [8]:
s.loc['r1']

'a'

In [9]:
s.iloc[1]

'b'

In [16]:
p_name = pd.DataFrame({
    "name": ["a","b","s"],
    "inst": ["1a","2d","3d"],
    "a": [12,1,44]
})
p_name

name inst   a
0    a   1a  12
1    b   2d   1
2    s   3d  44

In [12]:
band = pd.DataFrame(columns=['name','int','age'])

In [13]:
band

Empty DataFrame
Columns: [name, int, age]
Index: []

In [15]:
band.columns

Index(['name', 'int', 'age'], dtype='object')

In [17]:
p_name.head(1)

name inst   a
0    a   1a  12

In [18]:
predicate = p_name['a'] > 3
over_3 = p_name[predicate]
over_3

name inst   a
0    a   1a  12
2    s   3d  44