## Numpy

In [1]:
import numpy as np

arr = np.array([[1,2,3],[4,5,3]])
print(np)


<module 'numpy' from 'C:\\Python311\\Lib\\site-packages\\numpy\\__init__.py'>


In [2]:
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(arr.data)

2
(2, 3)
6
int32
4


In [3]:
arr = np.array([[1,2,3],[4,5,3]], dtype=np.int16)  # set the data types
print(arr)
print(arr.dtype)

[[1 2 3]
 [4 5 3]]
int16


In [4]:
row = np.array([1,2,3])
explicit_row = np.array([[1,2,3]])
explicit_col = np.array([[4],[5],[6]])
print(explicit_row)
print(explicit_col)


[[1 2 3]]
[[4]
 [5]
 [6]]


In [5]:
np.ones((2,2))
np.zeros((2,2))
np.full((3,2), 55)

array([[55, 55],
       [55, 55],
       [55, 55]])

In [6]:
np.linspace(0,99, num=10)

array([ 0., 11., 22., 33., 44., 55., 66., 77., 88., 99.])

In [7]:
np.arange(0, 99, 5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [8]:
#np.add
#np.subtract
#np.mutiply
#np.divide

In [9]:

arr = np.array([[1,2,3],[4,5,6]])
print(np.mean(arr))
print(np.std(arr))
print(np.min(arr))
print(np.max(arr))

3.5
1.707825127659933
1
6


In [10]:
arr.T.shape # transpose the array

(3, 2)

In [11]:
np.reshape(arr,(1,6))

array([[1, 2, 3, 4, 5, 6]])

In [12]:
# np.save np.load

## Pandas
Each column is a numpy array

In [13]:
import pandas as pd
pd.Series(['a','b','c','c'])  # one dimensional array


0    a
1    b
2    c
3    c
dtype: object

In [14]:
s = pd.Series(['a','b','c','c'],
         index=['r1','r2','r3','r4']
         )  # supplying a custom index

In [15]:
s.loc['r1'] # value by key 

'a'

In [16]:
s.iloc[1] # value by index

'b'

In [17]:
p_name = pd.DataFrame({
    "name": ["a","b","s"],
    "inst": ["1a","2d","3d"],
    "age": [12,1,44]
})
p_name

name inst  age
0    a   1a   12
1    b   2d    1
2    s   3d   44

In [18]:
# set the column names
band = pd.DataFrame(columns=['name','int','age'])

In [19]:
band

Empty DataFrame
Columns: [name, int, age]
Index: []

In [20]:
band.columns # tell me about the colunm names

Index(['name', 'int', 'age'], dtype='object')

In [21]:
p_name.head(1) # display the first row

name inst  age
0    a   1a   12

In [22]:
predicate = p_name['age'] > 3 
# select where a is grater than 3
over_3 = p_name[predicate]
over_3

name inst  age
0    a   1a   12
2    s   3d   44

In [30]:
## Reading and writing
grades = pd.read_csv('data/grades.csv')
grades.head()


Student ID         Name  Subject  Grade  Attendance
0           1   John Smith     Math     85          95
1           2     Jane Doe  Science     92         100
2           3   Mark Brown  English     78          90
3           4  Sarah Green  History     88          85
4           5     Alex Lee     Math     95         100

## Getting Summery Stats

In [35]:
grades['Grade'].mean()
# .medium

88.6

In [37]:
# descibe create a load of Summery Stats
grades.describe()

Student ID      Grade  Attendance  Normlised Grade
count    20.00000  20.000000   20.000000        20.000000
mean     10.50000  88.600000   92.500000         0.886000
std       5.91608   5.030434    6.786209         0.050304
min       1.00000  78.000000   80.000000         0.780000
25%       5.75000  86.500000   88.750000         0.865000
50%      10.50000  89.500000   95.000000         0.895000
75%      15.25000  92.000000  100.000000         0.920000
max      20.00000  96.000000  100.000000         0.960000

In [88]:
stats = pd.read_csv('data/us-states.csv')
stats_pop = stats[['population']].describe()
stats.head()

#stats_pop.iloc[[4,5,6],[0]]

#codes = stats.sort_values('order joined',  ascending=False).iloc[:,1].values.tolist()
#print(codes)

stats['GDP per cap'] = stats.iloc[:,3] * stats.iloc[:,2]

stats.head()

state code  population  GDP (billion USD)  order joined   GDP per cap
0     Alabama   AL     4849377                213            22    1032917301
1      Alaska   AK      736732                 50            49      36836600
2     Arizona   AZ     6731484                356            48    2396408304
3    Arkansas   AR     2966369                127            25     376728863
4  California   CA    38802500               3600            31  139689000000

In [23]:
## widgets
    # sliders
    # checkboxes

In [24]:
%matplotlib inline
import matplotlib.pyplot as plt
from ipywidgets import interact, interactive
import ipywidgets as widgets
import networkx as nx

# interact(f, x=widgets.IntSlider(min=-10, max=30, step=1, value=10));

def plot_random_binomial_graph(n, p, generator, layout):
    g = generator(n, p)
    pos = layout(g)
    nx.draw(g, pos=pos)
    plt.show()

interact(plot_random_binomial_graph, n=(2,20), p=(0.0, 1.0, 0.001),
         generator={'fast': nx.fast_gnp_random_graph, 'standard': nx.gnp_random_graph}, 
         layout={'shell_layout':nx.shell_layout, 'spring_layout': nx.spring_layout});

interactive(children=(IntSlider(value=11, description='n', max=20, min=2), FloatSlider(value=0.5, description=…

In [25]:
def f(x):
    return x

interact(f, x=10);

interactive(children=(IntSlider(value=10, description='x', max=30, min=-10), Output()), _dom_classes=('widget-…

In [26]:
    #interact(plot_random_binomial_graph, g = gf , layout={'shell_layout':nx.shell_layout, 'spring_layout': nx.spring_layout});

In [27]:
%matplotlib inline
import matplotlib.pyplot as plt
from ipywidgets import interact, interactive, fixed
import ipywidgets as widgets
import networkx as nx
from IPython.display import display

output = widgets.Output()
n = widgets.IntSlider(min = 2, max =20, value=10)


p = widgets.FloatSlider(min = 0.0, max =1.0, step=0.001, value=0.5)
#

g = widgets.Dropdown( 
    options=[('fast', nx.fast_gnp_random_graph), ('standard', nx.gnp_random_graph)],
    value=nx.fast_gnp_random_graph,
    description='generator:',
)

l = widgets.Dropdown( 
    options=[('shell_layout','nx.shell_layout'), ('spring_layout', 'nx.spring_layout')],
    value='nx.shell_layout',
    description='layout:',)

button = widgets.Button(description="Gen!")

class wid:
    def __init__(self):
        self.gen =''
        
    def update_ie(self,change):
         with output:
            output.clear_output()
            if change.new == 'nx.shell_layout':    
                nx.draw(self.gen, pos=self.g1)   
                plt.show()
            if change.new == 'nx.spring_layout':
                nx.draw(self.gen, pos=self.g2)   
                plt.show()

    def set_gen(self, n, p, generator):
        with output:
            self.gen = generator(n, p)
 
    def dsp(self):
        with output:
            output.clear_output()
            nx.draw(self.gen, pos=self.pos)   
            plt.show()

    def on_button_clicked(self,b):
        with output:
            print("Button clicked.")
            self.set_gen( n.value, p.value, g.value)
            self.g1 = nx.shell_layout(self.gen)
            self.g2 = nx.spring_layout(self.gen)
            output.clear_output()
            if l.value == 'nx.shell_layout':
                nx.draw(self.gen, pos=self.g1)   
                plt.show()
            if l.value == 'nx.spring_layout':
                nx.draw(self.gen, pos=self.g1)   
                plt.show()

            





wi = wid()




ie = widgets.interactive(wi.set_gen,  n = n, p = p, generator = g);

display(l)
display(ie)
display(output)
display(button)

button.on_click(wi.on_button_clicked)
l.observe(wi.update_ie, names='value')



Dropdown(description='layout:', options=(('shell_layout', 'nx.shell_layout'), ('spring_layout', 'nx.spring_lay…

interactive(children=(IntSlider(value=10, description='n', max=20, min=2), FloatSlider(value=0.5, description=…

Output()

Button(description='Gen!', style=ButtonStyle())